[workspace]
members = [
    "opentelemetry",
    "opentelemetry-contrib",
    "opentelemetry-datadog",
    "opentelemetry-http",
    "opentelemetry-jaeger",
    "opentelemetry-otlp",
    "opentelemetry-prometheus",
    "opentelemetry-aws",
    "opentelemetry-semantic-conventions",
    "opentelemetry-stackdriver",
    "opentelemetry-zipkin",
    "opentelemetry-zpages",
    "examples/actix-http",
    "examples/actix-http-tracing",
    "examples/actix-udp",
    "examples/async",
    "examples/aws-xray",
    "examples/basic",
    "examples/basic-otlp",
    "examples/basic-otlp-with-selector",
    "examples/basic-otlp-http",
    "examples/datadog",
    "examples/external-otlp-tonic-tokio",
    "examples/grpc",
    "examples/http",
    "examples/hyper-prometheus",
    "examples/tracing-grpc",
    "examples/zipkin",
    "examples/multiple-span-processors",
    "examples/zpages"
]
exclude = ["examples/external-otlp-grpcio-async-std"]

[patch.crates-io]
# revert tonic to 2018 edition so opentelemetry can use it
tonic = { git = "https://github.com/hyperium/tonic", rev = "101f2f76d4a62" } # branch = master
tonic-build = { git = "https://github.com/hyperium/tonic", rev = "101f2f76d4a62" } # branch = master
